name: CI

on:
  push:

jobs:
  build:
    timeout-minutes: 60
    strategy:
      # Don't cancel everything when one Go version fails
      fail-fast: false
      matrix:
        go:
          - "1.21.x" # Golang upstream stable
          - "1.22.x" # Golang upstream stable
          - "1.23.x" # Golang upstream stable
          - "1.24.x" # Golang upstream stable
        GOMAXPROCS:
          - "0" # Use all cpus (default).
          - "1" # Single-cpu mode. Some failures are only visible like this.

    name: Run CI with Go Version ${{ matrix.go }} & GOMAXPROCS ${{ matrix.GOMAXPROCS }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Make "git describe" work

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      # CI platform specific setup steps happen here
      - run: sudo apt-get install -qq fuse3 libssl-dev libfuse-dev
      - run: echo user_allow_other | sudo tee -a /etc/fuse.conf

      # Actual test steps are in all.bash
      - run: GOMAXPROCS="${{ matrix.GOMAXPROCS }}" ./all.bash
